import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar/app-sidebar";
import AuthDataLoader from "@/components/AuthDataLoader/AuthDataLoader";
import ReduxAppProvider from "@/redux/ReduxAppProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxAppProvider>
          <SidebarProvider>
            <SessionProvider>
              <AuthDataLoader />
              <AppSidebar />
              <div className="grow">
                <Navbar />
                {children}
              </div>
              <Toaster richColors />
            </SessionProvider>
          </SidebarProvider>
        </ReduxAppProvider>
      </body>
    </html>
  );
}
